config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'
  resources :users
  resources :groups do
    get :serch, on: :collection
  end
  
  resources :questions, except:[:new, :create, :edit, :update, :destroy] 
  post '/groups/:id/confirm-quiz', to: 'questions#confirm_quiz', as: 'confirm_quiz'
  get '/groups/:id/confirm-quiz', to: 'questions#new'
  get '/groups/:id/new-quiz', to: 'questions#new', as: 'new_quiz'
  post '/groups/:id/new-quiz', to: 'questions#create', as: 'quiz'
  get 'groups/:id/questions/:question_id/edit', to: 'questions#edit', as: 'edit_quiz'
  post 'groups/:id/questions/:question_id', to: 'questions#update', as: 'quiz_update'
  delete 'groups/:id/questions/:question_id', to: 'questions#destroy', as: 'delete_question'
  
  get '/groups/:id/answering', to: 'groups#answering', as: 'answering'
  post '/groups/:id/result', to: 'groups#show_result', as: 'show_result'
  post '/groups/:id/create-answer', to: 'groups#answer_create', as: 'answer_create'
  get '/groups/:id/result/correct', to: 'groups#correct_answer', as: 'correct_answer'
  get '/groups/:id/result/miss', to: 'groups#wrong_choice', as: 'wrong_choice'
  get '/groups/:id/result/score', to: 'groups#score_label', as: 'score_label'
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  get '/signup', to: 'users#new'
  get 'users/:id/delete-account', to: 'users#delete_account', as: 'delete_account'
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :group, optional: true
  has_many :choices, dependent: :destroy
  validates :content, presence: true
  default_scope { order(created_at: :desc) }
  scope :of_group, -> group { where(group_id: group.id)} 
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

before_action :logged_in_user, only: [:new, :confirm_quiz, :create, :create, :edit, :update, :destroy]

def new
  @user = current_user
  @group = Group.find_by(id: params[:id])
  @quiz = QuizForm.new
  @questions = Question.of_group(@group)
end

def confirm_quiz
  @group = Group.find(params[:id])
  @quiz = QuizForm.new(quiz_params)
  @questions = Question.of_group(@group)
  render :new unless @quiz.valid?
end

def create
  @user = current_user
  @group = Group.find(params[:id])
  @quiz = QuizForm.new(quiz_params)
  
  if params[:back].present?
    render :new
    return
  end
  
  if params[:done].present?
    @quiz.save
    redirect_to current_user
    flash[:success] = '　保存しました'
    return
  end
  
  if @quiz.save
    redirect_to new_quiz_path(@group)
    flash[:success] = '保存しました'
  else
    render :new
  end
end

def edit
  get_quiz
end

def update
  get_quiz
  
  if params[:back].present?
    redirect_to edit_group_path(@group)
    return
  end
  
  if quiz_update
    redirect_to edit_group_path(@group)
    flash[:success] = '更新しました'
  else
    render :edit
  end
end

def destroy
  @group = Group.find(params[:id])
  @question = Question.find(params[:question_id])
  @question.destroy
  redirect_to edit_group_path(@group), notice: '削除しました'
end

private
  def quiz_params
    params.require(:quiz_form).permit(
      :question_content,
      :question_user_id,
      :group_id,
      :answer,
      :wrong_choice_1,
      :wrong_choice_2,
      :wrong_choice_3)
  end
  
  def get_quiz
    @group = Group.find(params[:id])
    @question = Question.find(params[:question_id])
    @answer = @question.choices.find_by(is_answer: true)
    @wrong_choices = @question.choices.where(is_answer: false)
  end
  
  def quiz_update
    @question.update(content: params[:question_content]) &&
    @answer.update(content: params[:answer]) &&
    @wrong_choices[0].update(content: params[:wrong_choice_1]) &&
    @wrong_choices[1].update(content: params[:wrong_choice_2]) &&
    @wrong_choices[2].update(content: params[:wrong_choice_3])
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/confirm_quiz.html.slim
div.quiz-form.col-xs-12.col-sm-10.col-md-7.col-lg-5.mx-auto.mt-3

  =form_with model: @quiz, url: quiz_path, local: true, class: 'mx-auto quiz-confirm-form' do |f|
    .group-content.m-0.text-center  #{@group.content}  
  
    .question-count.mb-3.text-center 第#{@group.questions.count + 1}問
       
    = f.hidden_field :question_content
    
    = f.hidden_field :question_user_id, value: current_user.id
    
    = f.hidden_field :group_id, value: @quiz.group_id
    
    .form-group
        =f.label :question_content, '問題文'
        =f.text_area :question_content, disabled: true, value: @quiz.question_content, class: 'form-control'
        =f.hidden_field :question
    .form-group
        =f.label :answer
          =icon 'fas', 'check'
          |  正解の選択肢
        =f.text_field :answer, disabled: true, value: @quiz.answer, class: 'form-control'
        =f.hidden_field :answer
    .form-group.mt-5
        =f.label :wrong_choice_1
          =icon 'fas', 'times'
          |  ダミーの選択肢①
        =f.text_field :wrong_choice_1, disabled: true, value: @quiz.wrong_choice_1, class: 'form-control'
        =f.hidden_field :wrong_choice_1
    .form-group
        =f.label :wrong_choice_2
          =icon 'fas', 'times'
          |  ダミーの選択肢②
        =f.text_field :wrong_choice_2, disabled: true, value: @quiz.wrong_choice_2, class: 'form-control'
        =f.hidden_field :wrong_choice_2
    .form-group
        =f.label :wrong_choice_3
          =icon 'fas', 'times'
          |  ダミーの選択肢②
        =f.text_field :wrong_choice_3, disabled: true, value: @quiz.wrong_choice_3, class: 'form-control'
        =f.hidden_field :wrong_choice_3
    .attention-area.mx-auto
    .attention ・「次へ」または「完了」をクリックすると問題が保存されます
    -if @questions.count < 5
      .attention ・グループを有効にするには５問以上作成してください
    .btn-area.mt-4
      = f.submit '戻る',name: 'back', class: 'btn btn-secondary mr-auto'
      = f.submit '完了', name: 'done', class: 'btn btn-primary mx-auto'
      = f.submit '次へ', class: 'btn btn-success ml-auto'

app/views/questions/edit.html.slim
div.quiz-form.col-xs-12.col-sm-10.col-md-7.col-lg-5.mx-auto.mt-3
            
  =form_with model: @quiz, url: quiz_update_url, local: true, class: 'mx-auto quiz-edit-form' do |f|
    .group-content.m-0.text-center  #{@group.content} 
     

    =f.hidden_field :question_id, value: @question.id
    
    .form-group.mt-3
      =f.label :question_content, '問題文を記入'
      =f.text_area :question_content, class: 'form-control',value: @question.content
    .form-group
      =f.label :answer
        ==icon 'fas', 'check'
        |  正解の選択肢
      =f.text_field :answer, class: 'form-control answer',value: @answer.content
    .form-group.mt-5
      =f.label :wrong_choice_1
        =icon 'fas', 'times'
        |  ダミーの選択肢①
      =f.text_field :wrong_choice_1, class: 'form-control fake',value: @wrong_choices[0].content
    .form-group
      =f.label :wrong_choice_2
        =icon 'fas', 'times'
        |  ダミーの選択肢②
      =f.text_field :wrong_choice_2, class: 'form-control fake',value: @wrong_choices[1].content
    .form-group
      =f.label :wrong_choice_3
        =icon 'fas', 'times'
        |  ダミーの選択肢③
      =f.text_field :wrong_choice_3, class: 'form-control fake',value: @wrong_choices[2].content
      
    .btn-area.mt-5.mx-auto
      =f.submit '戻る',name: 'back', class: 'btn btn-secondary mx-auto'
      =f.submit '更新', id: 'quiz-update-btn', class: 'btn btn-primary mx-auto'

app/views/questions/new.html.slim
div.quiz-form.new-quiz-form.col-xs-12.col-sm-10.col-md-7.col-lg-5.mx-auto.mt-3
            
  =form_with model: @quiz, url: confirm_quiz_path, local: true, class: 'mx-auto' do |f|
    .group-content.m-0.text-center  #{@group.content}  
  
    .question-count.mb-3.text-center 第#{@group.questions.count + 1}問
    
    =f.hidden_field :question_user_id, value: current_user.id
    =f.hidden_field :group_id, value: @group.id
    
    .form-group.mt-3
      =f.label :question_content, '問題文を記入'
      =f.text_area :question_content, class: 'form-control'
    .form-group
      =f.label :answer
        =icon 'fas', 'check'
        |  正解の選択肢
      =f.text_field :answer, class: 'form-control answer'
    .form-group.mt-5
      =f.label :wrong_choice_1
        =icon 'fas', 'times'
        |  ダミーの選択肢①
      =f.text_field :wrong_choice_1, class: 'form-control fake'
    .form-group
      =f.label :wrong_choice_2
        =icon 'fas', 'times'
        |  ダミーの選択肢②
      =f.text_field :wrong_choice_2, class: 'form-control fake'
    .form-group
      =f.label :wrong_choice_3
        =icon 'fas', 'times'
        |  ダミーの選択肢③
      =f.text_field :wrong_choice_3, class: 'form-control fake'
    .btn
      =f.submit '確認', class: 'btn btn-secondary'