config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'
  resources :users
  resources :groups do
    get :serch, on: :collection
  end
  
  resources :questions, except:[:new, :create, :edit, :update, :destroy] 
  post '/groups/:id/confirm-quiz', to: 'questions#confirm_quiz', as: 'confirm_quiz'
  get '/groups/:id/confirm-quiz', to: 'questions#new'
  get '/groups/:id/new-quiz', to: 'questions#new', as: 'new_quiz'
  post '/groups/:id/new-quiz', to: 'questions#create', as: 'quiz'
  get 'groups/:id/questions/:question_id/edit', to: 'questions#edit', as: 'edit_quiz'
  post 'groups/:id/questions/:question_id', to: 'questions#update', as: 'quiz_update'
  delete 'groups/:id/questions/:question_id', to: 'questions#destroy', as: 'delete_question'
  
  get '/groups/:id/answering', to: 'groups#answering', as: 'answering'
  post '/groups/:id/result', to: 'groups#show_result', as: 'show_result'
  post '/groups/:id/create-answer', to: 'groups#answer_create', as: 'answer_create'
  get '/groups/:id/result/correct', to: 'groups#correct_answer', as: 'correct_answer'
  get '/groups/:id/result/miss', to: 'groups#wrong_choice', as: 'wrong_choice'
  get '/groups/:id/result/score', to: 'groups#score_label', as: 'score_label'
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  get '/signup', to: 'users#new'
  get 'users/:id/delete-account', to: 'users#delete_account', as: 'delete_account'
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user, optional: true
  has_many :questions, foreign_key: :group_id, dependent: :destroy
  validates :content, presence: true
  
  default_scope { order(updated_at: :desc) }
  
  scope :like, -> cont { where('content LIKE ?', "%#{cont}%")}
  scope :of_user, -> user { where(user_id: user.id) }
  scope :recent, -> { order(created_at: :desc) }

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

before_action :set_quiz, only: [:answering, :show_result, :correct_answer, :wrong_choice, :answer_create]
before_action :get_answer, only: [:correct_answer, :wrong_choice]
before_action :valid_groups, only: [:index, :serch]
before_action :logged_in_user, only: [:index, :serch, :new, :create, :edit, :update, :destroy]  
  
def index
  @groups = Kaminari.paginate_array(@valid_groups).page(params[:page]).per(10)
end

def serch
  if params[:cont].present?
    @serched_groups = Group.like(params[:cont]).page(params[:page]).per(10)
  else
    @serched_groups = []
  end
  @groups = Kaminari.paginate_array(@valid_groups).page(params[:page]).per(10)
end

def show
  @user = current_user
  @group = Group.find(params[:id])
  set_available_groups
  @questions = Question.of_group(@group)
end

def new
  @user = current_user
  @group = Group.new
  @groups = Group.of_user(@user)
end

def create
  @user = current_user
  @group = Group.new(group_params)
  @groups = Group.where(user_id: current_user.id)
  if @group.save
    redirect_to new_quiz_path(@group)
    flash[:success] = 'グループを作成しました'
  else
    render :new
  end
end

def edit
  @group = Group.find(params[:id])
end

def update
  @group = Group.find(params[:id])
  if @group.update(group_params)
    redirect_to edit_group_path(@group)
    flash[:success] = '更新しました'
  else
    render :edit
  end
end

def destroy
  @group = Group.find(params[:id])
  @group.destroy
  redirect_to current_user, notice: 'グループを削除しました'
end

def answering
  reset_count if @@quiz_num == 0
  @score = @@score
  @miss = @@miss
end

def show_result
  return if params[:choice_id].nil?
  @@quiz_num += 1 unless @@quiz_num >= @questions.count
  if correct?
    redirect_to correct_answer_url
  else
    redirect_to wrong_choice_url
  end
end

def correct_answer
end

def wrong_choice
end

def answer_create
  if params[:score_label].present?
    @@quiz_num = 0
    redirect_to score_label_url
    return
  end
  redirect_to answering_url
end

def score_label
  @group = Group.find(params[:id])
  @score = @@score
  @miss = @@miss
  @correct_answer_rate = ((@@score / @group.questions.count.to_f) * 100).round
  current_user.update_quiz_data(@@score, @group.questions.count) unless current_user.nil?
end

private
  def group_params
    params.require(:group).permit(:content, :user_id)
  end

  def set_quiz
    @group = Group.find(params[:id])
    set_available_groups
    @questions = Question.where(group_id: @group.id)
    @quiz_num = @@quiz_num
    @score = @@score
  end
  
  def correct?
    selected_choice = Choice.find(params[:choice_id])
    if selected_choice.is_answer
      @@score += 1  
      return true
    else
      @@miss += 1
      return false  
    end
  end
  
  def get_answer
    @answer = @group.questions[@quiz_num - 1].choices.find_by(is_answer: true)
  end
  
  def valid_groups
    @valid_groups = Group.all.reject { |group| group.questions.count < 5 }
  end

  def set_available_groups
    groups = Group.recent
    valid_groups = groups.reject { |group| group.questions.count < 5 }
    available_without_login = valid_groups.first(10)
    logged_in_user unless @group.in?(available_without_login)
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_group_list.html.slim
h6.mt-5.text-left.border-bottom.mx-auto.col-10.col-md-8.col-lg-6 クイズ一覧
-@groups.each do |group|
  .list-group.group-list.mx-auto.col-10.col-md-8.col-lg-6
    =link_to group.content, group_path(group), class: 'list-group-item list-group-item-action mt-1'
    p
      | Created by  
      -if group.user == current_user
        = link_to 'me', user_path(group.user)
      -else
          = link_to group.user.name, user_path(group.user)
          
  .pagination.mx-auto
    = paginate @groups

app/views/groups/_score_nav.html.slim
.score-nav.row
  .col-6.col-lg-8.col-xl-10
  .col-3.col-lg.col-xl-1.row
    .correct-icon.icon.col-6
      =icon 'fas', 'check'
    .correct-count.col-6 #{@score}
  .col-3.col-lg.col-xl-1.row
    .wrong-icon.icon.col-6
      =icon 'fas', 'times'
    .wrong-count.col-6 #{@miss}

app/views/groups/_show_result.html.slim
.show-result-form.col-xs-12.col-sm-10.col-md-7.col-lg-5.mx-auto
  
  =form_with url: answer_create_path, class: 'mx-auto' do |f|
    .answer-content.col-10.mx-auto.mb-3 A. #{@answer.content}
    -if @quiz_num == @questions.count
      =f.submit '結果を見る', name: 'score_label', class: 'btn btn-primary'
    -else
      =f.submit '次へ', class: 'btn btn-success'

app/views/groups/answering.html.slim
=render partial: 'score_nav'

div.quiz-form.answering-form.col-xs-12.col-sm-10.col-md-7.col-lg-5.mx-auto.mt-5
  =form_with url: show_result_path, class: 'answering-form mx-auto' do |f|
    -question = @questions[@quiz_num]
    
    .question.question-number 第#{(@quiz_num + 1).to_s}問
    .question.question-content.mb-5 #{question.content}
    
    -shuffled_choices = question.choices.shuffle
    
    
    .form-group.mx-auto.list-group
      =f.radio_button :choice_id, :"#{shuffled_choices[0].id}", id: 'choice1'
      =f.label :choice1, shuffled_choices[0].content, class: 'list-group-item'
    .form-group.mx-auto.list-group
      =f.radio_button :choice_id, :"#{shuffled_choices[1].id}", id: 'choice2'
      =f.label :choice2, shuffled_choices[1].content, class: 'list-group-item'
    .form-group.mx-auto.list-group
      =f.radio_button :choice_id, :"#{shuffled_choices[2].id}", id: 'choice3'
      =f.label :choice3, shuffled_choices[2].content, class: 'list-group-item'
    .form-group.mx-auto.list-group
      =f.radio_button :choice_id, :"#{shuffled_choices[3].id}", id: 'choice4'
      =f.label :choice4, shuffled_choices[3].content, class: 'list-group-item'
    .btn
      =f.submit '確認', class: 'btn btn-primary mt-3', id: 'next-btn'

  h6.group-title.mt-5.text-right
    | #{@group.content} 
    span.attention
      | 全#{@questions.count}問

app/views/groups/correct_answer.html.slim
=render partial: 'show_result'

.show-result-icon
  =icon 'fas', 'check'

app/views/groups/edit.html.slim
.row.col-xs-12.col-xs-12.col-sm-10.col-md-8.col-lg-6.mx-auto
  =link_to 'マイページに戻る', current_user, class: 'link mr-auto'

  =form_with model: @group, local: true, class: 'mx-auto col-12 mb-3 mt-5' do |f|
    .form-group.row
      =f.label :content, 'グループ名', class: 'col-12 mr-auto'
      =f.text_field :content, class: 'form-control col-10', id: 'user_name', value: @group.content
      =f.submit '変更', class: 'btn btn-success text-center col-1.5  ml-auto'
    
  .mx-auto.mb-5
    =link_to '問題を追加', new_quiz_path(@group), class: 'btn btn-primary mx-auto'
    
  -@group.questions.each do |question|
    .col-12.list-group-item.mt-3 #{question.content}
    .ml-auto
      =link_to '編集', edit_quiz_path(id: @group.id, question_id: question.id), class: 'col-6 p-0 my-auto link' 
      =link_to '削除', delete_question_path(id: @group.id, question_id: question.id), method: 'delete', data: { confirm: 'この問題を削除しますか？' }, class: 'col-6 pl-3 pr-0 my-auto link'

app/views/groups/index.html.slim
=render partial: 'group_list'

app/views/groups/new.html.slim
.new-group-form.mx-auto.col-xs-12.col-sm-10.col-md-7.col-lg-5.mx-auto.mt-3
  =form_with model: @group, local: true, class: 'group-name-form mx-auto' do |f|
    .form-group
      =f.text_field :content, placeholder: '新しいグループを作成', class: 'form-control'
    .form-group
      =f.hidden_field :user_id, value: @user.id

      =f.submit '問題の作成へ進む', class: 'btn btn-primary'

  div.col-10.created-groups.p-0.mx-auto
    h6.mt-5.text-center 既存のグループに問題を追加する
    -@groups.each do |group|
      .list-group.group-list
        =link_to group.content, new_quiz_path(group), class: 'list-group-item list-group-item-action mt-1'

app/views/groups/score_label.html.slim
-if @correct_answer_rate == 100
  #perfect.col-xs-12.col-sm-10.col-md-7.col-lg-5.mx-auto Perfect!!

.score-label.col-xs-12.col-sm-10.col-md-7.col-lg-5.mx-auto
  .row.score-label-main
    .col-6.row
      .correct-icon.icon.col-7
        =icon 'fas', 'check'
      .correct-count.col-5 #{@score}
    .col-6.row
      .wrong-icon.icon.col-7
        =icon 'fas', 'times'
      .wrong-count.col-5 #{@miss}
    
  .correct-answer-rate.mt-5 正答率 : #{@correct_answer_rate}%
  
  =link_to 'もう一度', answering_path(@group), class: 'btn btn-success mx-auto mt-5'
  
  .border.mt-3.mx-auto
  
  =link_to 'Home', root_path, class: 'btn btn-primary mx-auto mt-3'

app/views/groups/serch.html.slim
-if @serched_groups.count > 0
  p.text-center #{@serched_groups.count} 件のクイズがヒットしました
  -@serched_groups.each do |group|
    .list-group.group-list.mx-auto.col-10.col-md-8.col-lg-6
      =link_to group.content, group_path(group), class: 'list-group-item list-group-item-action mt-1'
      p
        | Created by  
        -if group.user == current_user
          = link_to 'me', user_path(group.user)
        -else
          = link_to group.user.name, user_path(group.user)
          
  .pagination.mx-auto
    = paginate @serched_groups

-if @serched_groups.count == 0 || @serched_groups.nil?
  p.text-center 検索結果に合うクイズはありませんでした
  
  =render partial: 'group_list'

app/views/groups/show.html.slim
.show-group.mx-auto.mt-5
  h1 =@group.content
  p 問題数: #{@group.questions.count}
  
  -if @group.questions.count >= 5
    =button_to '回答スタート', answering_path, method: 'get', class: 'btn btn-success mt-5'
  -elsif @group.questions.count < 5 && @user
   .attention まだ有効ではありません。あと#{5 - @group.questions.count}問作成してください。
  -else
   .attention まだ有効ではありません。

app/views/groups/wrong_choice.html.slim
=render partial: 'show_result'

.show-result-icon
  =icon 'fas', 'times'