config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'
  resources :users
  resources :groups do
    get :serch, on: :collection
  end
  
  resources :questions, except:[:new, :create, :edit, :update, :destroy] 
  post '/groups/:id/confirm-quiz', to: 'questions#confirm_quiz', as: 'confirm_quiz'
  get '/groups/:id/confirm-quiz', to: 'questions#new'
  get '/groups/:id/new-quiz', to: 'questions#new', as: 'new_quiz'
  post '/groups/:id/new-quiz', to: 'questions#create', as: 'quiz'
  get 'groups/:id/questions/:question_id/edit', to: 'questions#edit', as: 'edit_quiz'
  post 'groups/:id/questions/:question_id', to: 'questions#update', as: 'quiz_update'
  delete 'groups/:id/questions/:question_id', to: 'questions#destroy', as: 'delete_question'
  
  get '/groups/:id/answering', to: 'groups#answering', as: 'answering'
  post '/groups/:id/result', to: 'groups#show_result', as: 'show_result'
  post '/groups/:id/create-answer', to: 'groups#answer_create', as: 'answer_create'
  get '/groups/:id/result/correct', to: 'groups#correct_answer', as: 'correct_answer'
  get '/groups/:id/result/miss', to: 'groups#wrong_choice', as: 'wrong_choice'
  get '/groups/:id/result/score', to: 'groups#score_label', as: 'score_label'
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  get '/signup', to: 'users#new'
  get 'users/:id/delete-account', to: 'users#delete_account', as: 'delete_account'
end

app/models/user.rb
class User < ApplicationRecord
  before_save { email.downcase! }
  validates :name, presence: true, length: { maximum: 10 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, on: :create
  validates :password, presence: true, length: { minimum: 6 }, on: :with_password

  has_many :groups, foreign_key: :user_id, dependent: :destroy
  has_many :questions, foreign_key: :user_id, dependent: :destroy

  scope :rank, -> { order(total_score: :desc) }
  
  def update_quiz_data(score, count)
    score = self.total_score + score
    done = self.done_quiz_count + count
    self.update(total_score: score, done_quiz_count: done)
  end

  def accurancy
    if self.done_quiz_count == 0
      return 0
    else
      return ((self.total_score / self.done_quiz_count.to_f) * 100).round
    end
  end

  def point
    return self.total_score * 10
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:show, :edit, :update, :delete_account, :destroy]
  before_action :correct_user, only: [:edit, :update, :delete_account, :destroy]
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
      flash[:success] = 'アカウントが作成されました！'
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @groups = @user.groups
  end

  def index
    @users = User.rank.page(params[:page]).per(2)
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    @user.assign_attributes(user_params)
    if @user.valid?(:with_password) && @user.save
      redirect_to @user
      flash[:success] = '更新しました'
    else
      render :edit
    end
  end
  
  def delete_account
    @user = User.find(params[:id])
  end
  
  def destroy
    return unless params[:agree].present?
    User.find(params[:id]).destroy
    redirect_to root_path, notice: 'アカウントを削除しました'
  end
  
  private

    def user_params
      params.require(:user).permit(:name, :email, :image,
                                   :password, :password_confirmation)
    end
    
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless @user == current_user
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/delete_account.html.slim
.div#delete-account.mx-auto.mt-5
  h3.font-italic.col-sm-12.col-md-10.col-lg-6.mx-auto
    | #{@user.name} 
    span.font-weight-lighter さん
  
  .card.mx-auto.col-sm-12.col-md-10.col-lg-6.bg-light
    h1.card-title.text-center.pt-5 本当に削除しますか？
    ul.mt-5
      li ・あなたの作成したクイズもすべて削除されます
      li.pt-3 ・あなたの回答データも失われます
      li.pt-3 ・失われたデータは復元できません
    
    =form_with url: { coltroller: 'users', action: 'destroy' }, method: 'delete' do |f|
      .pt-5.pl-5
        =f.check_box :agree, include_hidden: false
        =f.label :agree, '確認しました', class: 'pl-3'
      .mx-auto.my-5.text-center
        =f.submit '削除', class: 'btn btn-danger col-3'
    

app/views/users/edit.html.slim
.user-form
  h6.edit-user-title プロフィール編集
  
  div.col-xs-12.col-sm-10.col-md-7.col-lg-5.mx-auto.mt-5
    =form_with model: @user, local: true do |f|
      .form-group
        =f.label :name, 'ユーザー名（10文字以内）'
        =f.text_field :name, class: 'form-control', id: 'user_name'
    
      .form-group
        =f.label :email, 'メールアドレス'
        =f.email_field :email, class: 'form-control', id: 'user_email'
        
      .form-group
        =f.label :password, 'パスワード'
        =f.password_field :password, class: 'form-control'
        
      .form-group
        =f.label :password_confirmation, 'パスワード（確認）'
        =f.password_field :password_confirmation, class: 'form-control'
        
      .btn.mx-auto.mt-3
        =f.submit '更新', class: 'btn btn-primary'
      
      .text-center.mx-auto.mt-3
        =link_to 'アカウント削除', delete_account_path(@user), class: 'attention'

app/views/users/index.html.slim
.list-group.col-xs-12.col-sm-10.col-md-8.col-lg-6.mx-auto
  h6.mt-5.text-left.border-bottom.col-12.mx-auto.mb-3 ランキング
  -@users.each do |user|
    -if user == current_user
      =link_to user_path(user), class: 'list-group-item list-group-item-action mx-auto active col-12 text-center mb-3 h3 rank-user-name'
        | #{user.name}
        span.d-inline-block -#{user.point}pt
          
    -else
      =link_to user_path(user), class: 'list-group-item list-group-item-action mx-auto  col-12 text-center mb-3 h3 rank-user-name'
        | #{user.name}
        span.d-inline-block -#{user.point}pt

  .pagination.mx-auto.mt-5
      = paginate @users

app/views/users/new.html.slim
.user-form
  h6 新規登録
  
  div.col-xs-12.col-sm-10.col-md-7.col-lg-5.mx-auto.mt-5
    =form_with model: @user, local: true do |f|
      .form-group.mt-5
        =f.label :name, 'ユーザー名（10文字以内）'
        =f.text_field :name, class: 'form-control', id: 'user_name'
    
      .form-group
        =f.label :email, 'メールアドレス'
        =f.email_field :email, class: 'form-control', id: 'user_email'
        
      .form-group
        =f.label :password, 'パスワード'
        =f.password_field :password, class: 'form-control'
        
      .form-group
        =f.label :password_confirmation, 'パスワード（確認）'
        =f.password_field :password_confirmation, class: 'form-control'
        
      .btn.mx-auto.mt-3
        =f.submit '登録', class: 'btn btn-primary'

app/views/users/show.html.slim
.user-profile.mx-auto
  .user-name.mx-auto
    p.m-0 ユーザー名
    .name.h2 #{@user.name}
    p.user-quiz-data.attention 作成したクイズ : #{@user.questions.count}問  　 正答率 : #{@user.accurancy}%
    
    
  
  -if @user == current_user
    =link_to edit_user_path
      =icon 'fas', 'ellipsis-h'
  
  -if @groups.any?
    h6.mt-5.text-left.border-bottom.col-xs-12.col-sm-10.col-md-8.col-lg-6.mx-auto 作成したクイズ
    -@groups.each do |group|
      .list-group.group-list.col-xs-12.col-sm-10.col-md-8.col-lg-6.mx-auto
        -if @user == current_user
          .row.mb-3
            =link_to group.content, group_path(group), class: 'list-group-item list-group-item-action mt-1 col-12'
            .ml-auto
              =link_to '編集', edit_group_path(group), class: 'col-6 p-0 my-auto link' 
              =link_to '削除', group, method: 'delete', data: { confirm: 'このグループのすべての問題が削除されます' }, class: 'col-6 p-0 my-auto link pl-3'
            
        -else
          =link_to group.content, group_path(group), class: 'list-group-item list-group-item-action mt-1 col-12'