config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'
  resources :users
  resources :groups do
    get :serch, on: :collection
  end
  
  resources :questions, except:[:new, :create, :edit, :update, :destroy] 
  post '/groups/:id/confirm-quiz', to: 'questions#confirm_quiz', as: 'confirm_quiz'
  get '/groups/:id/confirm-quiz', to: 'questions#new'
  get '/groups/:id/new-quiz', to: 'questions#new', as: 'new_quiz'
  post '/groups/:id/new-quiz', to: 'questions#create', as: 'quiz'
  get 'groups/:id/questions/:question_id/edit', to: 'questions#edit', as: 'edit_quiz'
  post 'groups/:id/questions/:question_id', to: 'questions#update', as: 'quiz_update'
  delete 'groups/:id/questions/:question_id', to: 'questions#destroy', as: 'delete_question'
  
  get '/groups/:id/answering', to: 'groups#answering', as: 'answering'
  post '/groups/:id/result', to: 'groups#show_result', as: 'show_result'
  post '/groups/:id/create-answer', to: 'groups#answer_create', as: 'answer_create'
  get '/groups/:id/result/correct', to: 'groups#correct_answer', as: 'correct_answer'
  get '/groups/:id/result/miss', to: 'groups#wrong_choice', as: 'wrong_choice'
  get '/groups/:id/result/score', to: 'groups#score_label', as: 'score_label'
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  get '/signup', to: 'users#new'
  get 'users/:id/delete-account', to: 'users#delete_account', as: 'delete_account'
end

app/views/layouts/_header.html.slim
nav.navbar.navbar-expand-lg.navbar-light.bg-light.sticky-top
  =link_to 'QuizUP!!', root_path, class: 'navbar-brand'
  -if logged_in?
    button.navbar-toggler type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"
      span.navbar-toggler-icon
  
    div#navbarSupportedContent.collapse.navbar-collapse
      ul.navbar-nav.mr-auto
        li.nav-item
          =link_to 'Quiz作成', new_group_path, class: 'nav-link'
        li.nav-item
          =link_to 'Quiz一覧', groups_path, class: 'nav-link'
        li.nav-item.dropdown
          a#navbarDropdown.nav-link href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" ユーザー情報 &#9662;
          div.dropdown-menu aria-labelledby="navbarDropdown"
            =link_to 'マイページ', user_path(current_user), class: 'dropdown-item'
            =link_to 'ランキング', users_path, class: 'dropdown-item'
            =link_to '登録情報編集', edit_user_path(current_user), class: 'dropdown-item'
            div.dropdown-divider.my-3
            =link_to  logout_path, method: 'delete', data: { confirm: 'ログアウトしてよろしいですか？' }, id: 'logout-link', class: 'dropdown-item'
              | ログアウト 
              =icon 'fas', 'sign-out-alt'
            =link_to 'アカウント削除', delete_account_path(current_user), class: 'dropdown-item attention'
      =form_with url: serch_groups_path, method: 'get', class: 'form-inline my-2 my-lg-0 col-xs-6', local: true do |f|
        =f.text_field :cont, placeholder: 'クイズを検索', type: 'serch', class: 'form-control mr-sm-2'
        =f.submit '検索', class: 'btn btn-outline-success my-2 my-sm-0'
        
  -else
    ul.navbar-nav.ml-auto
      li.nav-item
        =link_to 'ログイン', login_path, class: 'nav-link'
    li.nav-item.ml-3
      =link_to '新規登録', signup_path, class: 'btn btn-outline-primary'

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | QuizUP!!
    = csrf_meta_tags
    = csp_meta_tag
    meta content="width=device-width initial-scale=1.0 maximum-scale=1.0 minimum-scale=1.0" name="viewport"
    
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    
    script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"
    script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"
    script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"
  
  body
    =render partial: 'layouts/header'
    -flash.each do |message_type, message|
        div class="flash flash-#{message_type} text-center" #{message}   
    .container
      = yield